import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { WeatherProvider } from "@/Context/WeatherContext"
import { ForecastProvider } from "@/Context/ForecastContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Clima API",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <WeatherProvider>
        <ForecastProvider>
          <body className={inter.className}>{children}</body>
        </ForecastProvider>
      </WeatherProvider>
    </html>
  )
}
